### ISSUE TITLE
member cannot add info on Wiki成員無法在Wiki上添加資訊

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#103]
<img width="1289" alt="截圖 2024-06-07 上午10 29 24" src="https://github.com/3dw/auto20-next/assets/107933615/8e9cbd2e-b9dd-4073-b6e9-f451b2bdb69c">

as image.

**Comment by bestian** [comment]
權限開好了
https://github.com/3dw/auto20-next/wiki
