### ISSUE TITLE
Social sharing在Twitter上也要有圖

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#111]
https://socialsharepreview.com/?url=https://we.alearn.org.tw

**Comment by leechiuhui** [comment]
<img width="1107" alt="截圖 2024-06-11 上午9 57 13" src="https://github.com/3dw/auto20-next/assets/107933615/17f07cb8-2bb5-47bb-8901-c6a8fd74c00d">
在Ｘ（twitter)成功有圖了！！
https://socialsharepreview.com/?url=https://auto20-next.pages.dev/
