### ISSUE TITLE
「登入名簿」問題紀錄

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#121]
先記錄，暫時不處理。
1:在[we.alearn.org.tw/](https://we.alearn.org.tw/)的版本， 「登入名簿」button點下去似乎沒有任何作用。

2:在[https://auto20-next.pages.dev/。](https://auto20-next.pages.dev/%E3%80%82) 和 在http://localhost:8080/
點「登入名簿」有錯誤訊息如下：

Uncaught runtime errors:
×
ERROR
undefined is not an object (evaluating 'this.book.indexOf')
addBook@
addBook@[native code]
callWithErrorHandling@
callWithAsyncErrorHandling@
emit@
emit@[native code]
addBook@
addBook@[native code]
callWithErrorHandling@
callWithAsyncErrorHandling@
emit@
emit@[native code]
addBook@
addBook@[native code]
callWithErrorHandling@
callWithAsyncErrorHandling@
invoker@

**Comment by bestian** [comment]
那是因為名簿串列是不存在時, 程式應該(卻沒有)新創一個空串列再做後續

**Comment by leechiuhui** [comment]
thanks teacher's info and instrution.

**Comment by leechiuhui** [comment]
Just tested, and this issue has already been resolved by the teacher, Bestian.  by [cc40284](https://github.com/3dw/auto20-next/commit/cc40284787041f7e371154486b00c9b8d278c9db) Thank you~
