### ISSUE TITLE
剛剛確認（因為之前我這邊有的瀏覽器連不上，有的可連上，但剛剛發現原來可連上是因為是cookies留存），所以要回報❗️❗️https://we.alearn.org.tw至今應該已經持續好幾天都已經無法連上了啊！

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#125]
![image](https://github.com/3dw/auto20-next/assets/107933615/43e65013-cd81-4f99-8edf-f41b6d821ad1)

**Comment by bestian** [comment]
是3天. 查了一下應該是CNAME設定的問題
剛剛在public資料夾多放一次CNAME, 設成 we.alearn.org.tw

然後跑

``` sh deploy.sh ```

即解決了


之後如果要檢修
可以從專案的

settings > pages查到目前gh-pages發佈的位置正不正確.

謝謝

**Comment by leechiuhui** [comment]
Thank you, teacher. After I reported this issue last night, I received issues regarding Future Planet's electronic invoices and changes needed for the Universe School videos. I have been working on these since last night until now. Originally, Tuesdays and Fridays were my dedicated workdays for 3dw, but I realized that these current issues with Auto-next2.0 are quite challenging for me. I need more time to research them. This information is provided for your reference.

**Comment by bestian** [comment]
> Thank you, teacher. After I reported this issue last night, I received issues regarding Future Planet's electronic invoices and changes needed for the Universe School videos. I have been working on these since last night until now. Originally, Tuesdays and Fridays were my dedicated workdays for 3dw, but I realized that these current issues with Auto-next2.0 are quite challenging for me. I need more time to research them. This information is provided for your reference.

不急, 慢慢來

**Comment by leechiuhui** [comment]
> 是3天. 查了一下應該是CNAME設定的問題 剛剛在public資料夾多放一次CNAME, 設成 we.alearn.org.tw
> 然後跑
 > `sh deploy.sh`
  > 即解決了
 > 之後如果要檢修 可以從專案的
 > settings > pages查到目前gh-pages發佈的位置正不正確.

It seems that in 3dw/Auto20-next, I don't have the permissions to access the settings, as I can't find them anywhere.
<img width="1502" alt="截圖 2024-06-24 晚上11 18 29" src="https://github.com/3dw/auto20-next/assets/107933615/56dbed99-8c87-4d96-b97e-295945c826f1">

**Comment by bestian** [comment]
我開admin權限了
