### ISSUE TITLE
「群聊」的留言功能有 error

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#130]
Uncaught runtime errors:
×
ERROR
undefined is not an object (evaluating 'this.user.providerData[0]')
preview@
callWithErrorHandling@
callWithAsyncErrorHandling@
invoker@

**Comment by bestian** [comment]
可以改用this.users[this.uid].name代替this.user.providerData[0]並且在沒有this.users[this.uid]時用v-if藏住留言鈕和留言框

**Comment by leechiuhui** [comment]
**Teacher, I later found out that many people's Google account display names were undefined, so changing it this way resolved the issue.**
 
 var o = {
            uid: this.uid,
            //n: this.user.providerData[0].displayName,
            //n: this.user && this.user.providerData && this.user.providerData[0] ? this.user.providerData[0].displayName : 'Anonymous',
            //很多人的displayname是undefined，所以改成這樣
            n: this.user && this.user.providerData && this.user.providerData[0] ? this.user.providerData[0].displayName : this.user.name,
            t: this.msg,
            l: this.label,
            photoURL: this.photoURL || '',
            time: (new Date()).getTime()
          };
