### ISSUE TITLE
Firebase chat data was gone/deleted?

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#140]
Firebase chat data was gone/deleted?

**Comment by bestian** [comment]
應該是程式的bug造成的.
Firebase權限我改成只有登入者能讀寫之後
有的使用者沒有讀到chat的資料
但是寫入時覆蓋了全部的資料

**Comment by leechiuhui** [comment]
Firebase 我啟動備份了。

**Comment by bestian** [comment]
@leechiuhui 
謝謝, 我把程式碼修了一下, 讓它不會再全部覆寫了

**Comment by leechiuhui** [comment]
Thank you, teacher. I am studying the difference between these pieces of code.

**Comment by bestian** [comment]
<img width="491" alt="截圖 2024-07-05 下午2 51 54" src="https://github.com/3dw/auto20-next/assets/109048/5ba04667-1ec9-4ef3-a3a8-91e71ac011e1">

@leechiuhui 
主要是set 如果對整個chats 作用，它就會覆蓋掉所有的聊天資料
把它改成對 chats/(某個id) 作用，它就只會寫入一筆聊天資料
