### ISSUE TITLE
about  notion page embeded / or href

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#142]
https://galacticproject.notion.site/a0a32d5d4ddf43b28ae6a73c073e1c8c?v=72e87b01f9844b849d442458fe46aa04

"Preliminary reference materials from ChatGPT queries. Expected to be studied on weekdays (Tuesday or Friday). However, Teacher Tang   or anyone else who is available can handle it first.

要將 Notion 網頁嵌入到 Vue 3 網頁中，你可以使用 `<iframe>` 元素來實現。以下是詳細步驟和程式碼範例：

1. **建立 Vue 3 項目**（如果你還沒有項目）：
   - 使用 Vue CLI 或 Vite 建立一個新的 Vue 3 項目。

2. **在 Vue 組件中嵌入 Notion 網頁**：
   - 在你的 Vue 組件中使用 `<iframe>` 元素來嵌入 Notion 網頁。

以下是具體程式碼範例：

### 建立新的 Vue 項目（如果還沒有）

```bash
# 使用 Vue CLI
vue create my-vue-project
cd my-vue-project

# 或使用 Vite
npm init vite@latest my-vue-project --template vue
cd my-vue-project
npm install
```

### 在 Vue 項目中嵌入 Notion 網頁

1. **編輯 `src/App.vue`** 或建立新的 Vue 組件，例如 `src/components/NotionEmbed.vue`。

2. **使用 `<iframe>` 元素嵌入 Notion 網頁**：

`src/App.vue` 的範例程式碼：

```vue
<template>
  <div id="app">
    <h1>嵌入 Notion 網頁</h1>
    <iframe
      src="https://galacticproject.notion.site/a0a32d5d4ddf43b28ae6a73c073e1c8c?v=72e87b01f9844b849d442458fe46aa04"
      width="100%"
      height="800px"
      frameborder="0"
      allowfullscreen
    ></iframe>
  </div>
</template>

<script>
export default {
  name: 'App',
};
</script>

<style>
#app {
  text-align: center;
}

iframe {
  border: none;
}
</style>
```

或者，你可以建立一個新的組件，例如 `NotionEmbed.vue`：

`src/components/NotionEmbed.vue` 的範例程式碼：

```vue
<template>
  <div class="notion-embed">
    <iframe
      src="https://galacticproject.notion.site/a0a32d5d4ddf43b28ae6a73c073e1c8c?v=72e87b01f9844b849d442458fe46aa04"
      width="100%"
      height="800px"
      frameborder="0"
      allowfullscreen
    ></iframe>
  </div>
</template>

<script>
export default {
  name: 'NotionEmbed',
};
</script>

<style>
.notion-embed iframe {
  border: none;
}
</style>
```

3. **在 `App.vue` 中使用 `NotionEmbed` 組件**：

`src/App.vue` 的範例程式碼：

```vue
<template>
  <div id="app">
    <h1>嵌入 Notion 網頁</h1>
    <NotionEmbed />
  </div>
</template>

<script>
import NotionEmbed from './components/NotionEmbed.vue';

export default {
  name: 'App',
  components: {
    NotionEmbed,
  },
};
</script>

<style>
#app {
  text-align: center;
}
</style>
```

這樣，你的 Notion 網頁就會嵌入到你的 Vue 3 網頁中並顯示出來。如果有任何進一步的問題或需要更詳細的說明，歡迎隨時提問！

### `src/App.vue` 的範例程式碼

`App.vue` 使用 Pug 語法：

```vue
<template lang="pug">
  #app
    h1 嵌入 Notion 網頁
    iframe(
      src="https://galacticproject.notion.site/a0a32d5d4ddf43b28ae6a73c073e1c8c?v=72e87b01f9844b849d442458fe46aa04"
      width="100%"
      height="800px"
      frameborder="0"
      allowfullscreen
    )
</template>

<script>
export default {
  name: 'App',
};
</script>

<style>
#app {
  text-align: center;
}

iframe {
  border: none;
}
</style>
```

### `src/components/NotionEmbed.vue` 的範例程式碼

`NotionEmbed.vue` 使用 Pug 語法：

```vue
<template lang="pug">
  .notion-embed
    iframe(
      src="https://galacticproject.notion.site/a0a32d5d4ddf43b28ae6a73c073e1c8c?v=72e87b01f9844b849d442458fe46aa04"
      width="100%"
      height="800px"
      frameborder="0"
      allowfullscreen
    )
</template>

<script>
export default {
  name: 'NotionEmbed',
};
</script>

<style>
.notion-embed iframe {
  border: none;
}
</style>
```

### 在 `App.vue` 中使用 `NotionEmbed` 組件

```vue
<template lang="pug">
  #app
    h1 嵌入 Notion 網頁
    NotionEmbed
</template>

<script>
import NotionEmbed from './components/NotionEmbed.vue';

export default {
  name: 'App',
  components: {
    NotionEmbed,
  },
};
</script>

<style>
#app {
  text-align: center;
}
</style>
```

以上是將 Vue 項目中嵌入 Notion 網頁的範例程式碼改寫為 Pug 語法的版本。如果有任何進一步的問題或需要更多的幫助，請隨時告訴我！

**Comment by bestian** [comment]
@leechiuhui 
我試過iframe了, Noion不允許站外嵌入,
GPT應該是不知道這件事所以生成了錯誤的回答。

我想可以改用超連結，新增一個"友站連結"頁面來處理

**Comment by leechiuhui** [comment]
<img width="685" alt="截圖 2024-07-09 上午10 08 04" src="https://github.com/3dw/auto20-next/assets/107933615/4126ba1d-5624-4d50-927c-c474af00dcca">

Gemini Pro provided the answer. I have asked @ziaosen on Slack and will try again.

**Comment by bestian** [comment]
@leechiuhui 

我之前用私訊和 @ziaosen 有聊過，他說官方嵌入 是一個付費服務. 
個人認為是沒有必要為了嵌入額外付費. 超連結的方式也是很好的.

**Comment by leechiuhui** [comment]
![image](https://github.com/3dw/auto20-next/assets/107933615/bcfdec84-055a-43d1-b3b7-56dffb3b4e17)

Yes,sir.

**Comment by leechiuhui** [comment]
The private message!
It seems that ziaosen might not mean that Notion needs to be paid… it seems he said a third party  need to be paid😶‍🌫️ FYI![image](https://github.com/3dw/auto20-next/assets/107933615/a9857668-3912-45bf-8143-263f848bb4d5)

**Comment by leechiuhui** [comment]
YES!成功了
<img width="1476" alt="截圖 2024-07-09 下午4 40 08" src="https://github.com/3dw/auto20-next/assets/107933615/344a377a-92af-49aa-a25a-9515308806c2">

**Comment by leechiuhui** [comment]
However, after taking a closer look, I realized that what I thought was free will actually expire after 7 days. 🫠

**Comment by bestian** [comment]
I think we can use hyper-reference instead of iframe embed .

**Comment by leechiuhui** [comment]
Certainly, teacher. Will remove it and change it to a hyperlink. 
Simply enjoy trying new things I haven't experienced before.
