### ISSUE TITLE
功能許願：notifications( 初步完成，但是小紅點的計數有問題，一直是0，待檢修)

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#152]
說明：在自己參與的社團若有新建的資源或留言時，可以收到notification，就不必每次登入時主動點入社團去檢查

切豆腐：

- [x] 右上角的鈴噹和小紅點
- [x] users/$uid/notifcaions <-- 資料結構為Array of Objects ( time, from, text, route, isRead)

**Comment by leechiuhui** [comment]
@bestian 
sorry..here comes the question
how to updated the firebase Array of Objects  from image1 to image 2
<img width="224" alt="截圖 2024-07-26 下午5 49 36" src="https://github.com/user-attachments/assets/24019045-1eec-4ace-abcc-06a43b97aa0b">
<img width="398" alt="截圖 2024-07-26 下午5 49 52" src="https://github.com/user-attachments/assets/bde22197-319f-4448-8178-f713e2056a11">
Thanks,teacher.(sweat smile)

**Comment by leechiuhui** [comment]
or can the Array of Objects  could be like this (as the image)?
<img width="525" alt="截圖 2024-07-26 下午6 13 48" src="https://github.com/user-attachments/assets/9cc5a8a6-afba-46d1-a0e3-f4e49c2ef48c">
Thanks,teacher.

**Comment by bestian** [comment]
> @bestian sorry..here comes the question how to updated the firebase Array of Objects from image1 to image 2 <img alt="截圖 2024-07-26 下午5 49 36" width="224" src="https://private-user-images.githubusercontent.com/107933615/352488341-24019045-1eec-4ace-abcc-06a43b97aa0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTE2MTcsIm5iZiI6MTcyMTk5MTMxNywicGF0aCI6Ii8xMDc5MzM2MTUvMzUyNDg4MzQxLTI0MDE5MDQ1LTFlZWMtNGFjZS1hYmNjLTA2YTQzYjk3YWEwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxMDU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGY0ZWMzZjE4ZmY0MTlmZGNlNzk2ZTY4YzZiZmExNDRkZjhkODI2ZmY1NTc4ZDEwNGIxYjAxOGRkMjUwYjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FMbT6zY4gisRW8dfcUEcAnhNUHuK6Y51XCn-0Zz6E_0"> <img alt="截圖 2024-07-26 下午5 49 52" width="398" src="https://private-user-images.githubusercontent.com/107933615/352488355-bde22197-319f-4448-8178-f713e2056a11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTE2MTcsIm5iZiI6MTcyMTk5MTMxNywicGF0aCI6Ii8xMDc5MzM2MTUvMzUyNDg4MzU1LWJkZTIyMTk3LTMxOWYtNDQ0OC04MTc4LWY3MTNlMjA1NmExMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxMDU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDU3N2E0MmI0NGFlZGMzOGM0YTgxZmJmNzllZGIxNmQ3YzAyYWFiY2Y2OTIyNTczOGNmY2IwZDAzNDI3NGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8_yYLkH0MW-HTYCUvJ37JhZOvMHQba7hh9ZACfjy7nE"> Thanks,teacher.(sweat smile)


$uid 代表使用者的uid.

可以用set的方法

像是諸如 set(usersRef, '/' + this.uid + '/notifications/' + n, obj).then(() => { console.log('notification created')})

之類的

**Comment by leechiuhui** [comment]
進度更新：
暫時更新setupGroupListeners()但尚未解決onChildAdded不適當觸發以及舊資料觸發
<img width="954" alt="截圖 2024-07-27 下午6 08 04" src="https://github.com/user-attachments/assets/80d9f3f0-bcfa-4c9d-8d8a-f334aa8620f3">
Will fight again on Tuesday, 7/30. Your suggestions are welcome!XD

**Comment by bestian** [comment]
在邏輯上，onChildAdded 好像在使用者在線才會觸發
是不是可以改成在Group.view的addChat函式去主動發送通知?

**Comment by bestian** [comment]
我寫了相關的psudocode在Group.view裡，請參考

**Comment by sunshinejohnny** [comment]
感恩老師 
Danke schön

**Comment by leechiuhui** [comment]
Thank you teacher,will refer on it.Danke schön.

**Comment by bestian** [comment]
初步完成，但是小紅點的計數有問題，一直是0，待檢修

**Comment by bestian** [comment]
我猜想用watcher來監聽uid，確保uid有值時就get一次notifications，應該就可以解決了?

**Comment by leechiuhui** [comment]
目前測試：新建留言時，並不會add新的Notification.

**Comment by bestian** [comment]
@leechiuhui 這是因為Profile.vue的updateFlag函式有問題，先嘗試修正程式碼了，但時間不足以測試。
麻煩有空測試確認修好後，再close這個bug issue，感謝~
