### ISSUE TITLE
刪除旗幟後，第一時間查詢“夥伴”頁面時還是顯示出來。必須reload重新登入後，才會沒有在”夥伴“頁面顯示出來。

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#160]

**Comment by bestian** [comment]
可以試試看用
location.reload()
強制重新載入

**Comment by leechiuhui** [comment]
謝謝老師。昨晚比較晚了，當時測試後我升起的問題是：**Vue的程式碼不是應該可以直接渲染嗎？**
所以我剛剛問了，ChatGpt。[如下圖]
<img width="915" alt="截圖 2024-08-27 下午2 03 27" src="https://github.com/user-attachments/assets/0691d908-347d-46c2-89f8-304b96895f09">
<img width="902" alt="截圖 2024-08-27 下午2 03 35" src="https://github.com/user-attachments/assets/c60a2315-012a-4dd6-b95e-49a188f446ac">

(https://chatgpt.com/share/36a94b7f-24c5-43d8-ba71-f1960bef1658)

我將自己研究一下，如果您有空回覆也萬分感謝～

**Comment by bestian** [comment]
如果要避開使用location.reload()
可以使用this.$nextTick()

[https://chatgpt.com/share/1f9072a4-50ce-4f0d-b3f7-747aadbd94c4](https://chatgpt.com/share/1f9072a4-50ce-4f0d-b3f7-747aadbd94c4)

**Comment by bestian** [comment]
另外，原本的程式碼中，登出的時候，沒有把之前有權限拿到的所有使用者資料從用戶端拿掉。 可能這是造成問題的主要原因。
我在656d8ab的commit中補上了這段代碼。

麻煩再測試一下看看。

**Comment by leechiuhui** [comment]
.....目前情況是：刪除旗幟後，會自動被Logout，所以要進入“夥伴”頁面，或是“社團”頁面當然就會需要重新登入，所以進去“夥伴”或“社團”後沒有顯示此已經“刪除旗幟”的user是OK/正常發揮的......。
但是....當使用者只是“刪除旗幟”後，就直接被“登出”，這樣會不會...有點點怪怪的.......?

另目前有個挺好的優點，使用者“刪除旗幟”後，當他再次“升起旗幟”時，他之前所加入的社團會再次顯示出來。

**Comment by bestian** [comment]
我覺得直接登出不會奇怪，因為使用者如果要刪除旗幟的話，就表示他不想要再留在這個平台上了。從UX的角度好像這樣比較順，因為如果使用者只是想要改旗幟的話，他用修改的就好。
