### ISSUE TITLE
"刪除旗幟"後，目前暫測有再出現兩個Bug。

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#161]
目前暫測有再出現兩個Bug：

Bug1："刪除旗幟"->重新登入後->先點選社團->會只有出現"輸入社團名稱"框 要再點選"夥伴"，然後點選"社團"才會正常出現
<img width="1413" alt="截圖 2024-08-27 晚上8 41 29" src="https://github.com/user-attachments/assets/03a587cf-ffbe-4a39-ae09-dab717f89fa3">

Bug2："刪除旗幟"->重新登入後->先點選社團->會只有出現"新增社團"框 要再點選"夥伴"，然後點選"社團"才會正常出現後->發現即使這個user還沒有升起旗幟，但因為刪除旗幟前已加入該社團，所以在沒有“升起旗幟”的狀況下可進入社團->"編輯社團資料"。

<img width="1406" alt="截圖 2024-08-27 晚上8 49 38" src="https://github.com/user-attachments/assets/f9e299be-2d5e-425e-9aa7-d78648a0ddca">

**Comment by bestian** [comment]
both bug 1&2 are fixed
