### ISSUE TITLE
新加入的用戶資料的default值

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#162]
- [x] connect_me 預設為他的 email
- [ ] name 預設為google login可以抓到的display_name

**Comment by leechiuhui** [comment]
為了要處理這個issue ，先發現了一個bug,想了有點久想不出來（太燒腦了 哈哈），因為明天要直播，所以先暫時放下....這個問題情況請看下面錄製影片
https://www.loom.com/share/bddb318ff4e54a7596abc9611b833b29?sid=6c3eeb4b-214d-484e-a439-ed8d60f7cd91

**Comment by leechiuhui** [comment]
剛剛測試，重新定向個人頁的問題已經在[b6d5f1e](https://github.com/3dw/auto20-next/commit/b6d5f1e55ee13ad42ba0d0038bc595ebf5bb5a6a) 被解決，但是影片錄製主要要提的一個比較奇怪的問題是：
「在第一次編輯 profile時不會出現這個issue 所要達到的需求（connect_me 預設為他的 email 和
 name 預設為google login可以抓到的display_name
 ），而要reload再次登入後才會出現？」

 我現在研究一下，所以先reopen this issue... 🫡

**Comment by leechiuhui** [comment]
<img width="588" alt="截圖 2024-09-02 晚上11 50 18" src="https://github.com/user-attachments/assets/0dd220e2-feaa-4047-9847-6eb9b9b02e9c">
<img width="460" alt="截圖 2024-09-02 晚上11 51 26" src="https://github.com/user-attachments/assets/bdac36f3-1d73-4cd6-8417-85833f91590d">
目前花了四個小時測試研究，還是搞不懂：
為何第一次點選“我的旗幟”進來時，進到fetchUserData()  可以抓到uid 和 email 但就是沒有this.user.providerData[0].displayName ;而重新reload->登入後，不用進到fetchUserData() 就可以有this.user.providerData[0].displayName

目前11:55PM先到此暫停.....

**Comment by bestian** [comment]
@leechiuhui 
原本的loginGoole會抓this.users[this.uid]來賦值給this.user, 但Firebase中存的資料並不包含完整的providerData，因為用不到也不必要把google auth傳回到全部拿起來公開在網路上，應該是這樣導至有時沒有拿到providerData

所以我更新了loginGoole，每次login時都把profileData保留住，在用戶端重新餵給已被賦值後的this.user

經過測試問題已解決。

以下是新的loginGoogle函式：

```

loginGoogle: function (autoredirect) {
        // eslint-disable-next-line @typescript-eslint/no-this-alias
        const vm = this;
        if (this.isInApp) {
          window.alert('本系統不支援Facebook, Line等App內部瀏覽，請用一般瀏覽器開啟，方可登入，謝謝');
        } else {
          signInWithPopup(auth, provider).then((result) => {
            const user = result.user;
            console.log(user);

            vm.showLogin = false;
            vm.email = user.providerData[0].email;
            vm.uid = user.uid;
            vm.photoURL = user.photoURL ? decodeURI(user.photoURL) : "https://we.alearn.org.tw/logo-new.png";

            const pvdata = user.providerData; // 讓providerData保留

            if (vm.users && vm.users[vm.uid]) {
              vm.user = { ...vm.users[vm.uid], providerData: pvdata };  //無論如何保留住providerData
              vm.updateNotifications();
              if (vm.user.latlngColumn) {
                vm.locate(vm.user, false);
              }
            } else {
              get(usersRef).then((snapshot) => {
                const data = snapshot.val();
                vm.users = data;
                vm.user = { ...vm.users[vm.uid], providerData: pvdata };  //無論如何保留住providerData 
                vm.updateNotifications();
                if (vm.user.latlngColumn) {
                  vm.locate(vm.user, false);
                }
              }).catch((error) => {
                vm.user = { providerData: pvdata };  //無論如何保留住providerData
                console.error("Error fetching users:", error);
              });
            }

            if (autoredirect) {
              vm.$nextTick().then(() => {
                vm.$router.push('/profile');
              });
            }
          }).catch((error) => {
            console.error("Login error:", error);
            if (error.message.includes('sessionStorage')) {
              window.alert('瀏覽器不支持sessionStorage，請檢查瀏覽器設置或更換瀏覽器再試一次。');
            }
          });
        }
      },

```

**Comment by leechiuhui** [comment]
研讀相關commits完畢，感謝老師詳細教學。🫡
<img width="1337" alt="截圖 2024-09-04 下午2 03 31" src="https://github.com/user-attachments/assets/30c120d8-6af1-406f-880a-b4f0bc7c7ccb">

**Comment by bestian** [comment]
不客氣，我覺得程式碼之後還可以再簡化一點，例如重複的程式碼可以合併成函式。不過我是先把功能處理好，事後再看看是否能夠簡化
