### ISSUE TITLE
需要notify的事件

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#165]
- [x] 加入的社團底下出現新留言
- [x] 加入的社團底下出現新的資源

**Comment by leechiuhui** [comment]
done

**Comment by bestian** [comment]
沒有看到新的commit ?

**Comment by leechiuhui** [comment]
> 沒有看到新的commit ?
有喔 ，在這裏。
https://github.com/3dw/auto20-next/commit/29f1d3fe11582a7789c06cc42bb7e2939f48397b

**Comment by bestian** [comment]
> > 沒有看到新的commit ?
> > 有喔 ，在這裏。
> > [29f1d3f](https://github.com/3dw/auto20-next/commit/29f1d3fe11582a7789c06cc42bb7e2939f48397b)

現在有了。
