### ISSUE TITLE
功能許願：將login 改為一個component，並包含新的功能

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#168]
- [x] 創立testOnly switcher
- [x] 創立login component
- [x] 浮出該component在畫面的正中間，並以半透明的方式遮照全畫面
- [x] 新增keep me logged in功能 > [Firebase 持續性 技術文檔](https://firebase.google.com/docs/auth/web/auth-state-persistence?hl=zh-tw)

note: 這是重大更新，完成前先不要deploy到正式網站~

**Comment by bestian** [comment]
@leechiuhui 

我今天把keep me logged in功能做出來了，但程式碼還有點髒，也還沒有全部測完可能的bug
我想 #180 #181 之後再做好了，先切割成兩個新議題

這個#168本身的項目如果測試完了都ok, 就煩請build出來 & close this issue吧，多謝~

**Comment by leechiuhui** [comment]
**SOS**
@bestian **### Login.vue 有ＢＵＧ～～～～如下**


(base) chiuhuilee@ChiudeMacBook-Pro 3dw20240705auto20-next % yarn serve
yarn run v1.22.19
$ vue-cli-service serve
 INFO  Starting development server...


 ERROR  Failed to compile with 1 error                                                                                                 下午6:12:23

 error  in ./src/components/Login.vue?vue&type=script&lang=js

Syntax Error: TypeError: Cannot read properties of null (reading 'content')


ERROR in ./src/components/Login.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/Login.vue?vue&type=script&lang=js)
Module Error (from ./node_modules/vue-loader/dist/index.js):
[vue/compiler-sfc] Unexpected token, expected ")" (27:109)

/Users/chiuhuilee/Documents/GitHub/3dw20240705auto20-next/src/components/Login.vue
70 |        var autoredirect = true;
71 |  
72 |        if (this.$route.path === '/friends' || this.$route.path === '/maps' || $route.path.startsWith('/flag') {
   |                                                                                                               ^
73 |          autoredirect = false;
74 |        }
 @ ./src/components/Login.vue?vue&type=script&lang=js 1:0-197 1:0-197 1:198-384 1:198-384
 @ ./src/components/Login.vue 2:0-56 3:0-51 3:0-51 8:49-55
 @ ./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/App.vue?vue&type=script&lang=ts 9:0-43 36:4-9
 @ ./src/App.vue?vue&type=script&lang=ts 1:0-224 1:0-224 1:225-438 1:225-438
 @ ./src/App.vue 2:0-54 3:0-49 3:0-49 8:49-55
 @ ./src/main.ts 2:0-28 21:22-25

ERROR in ./src/components/Login.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/Login.vue?vue&type=script&lang=js)
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of null (reading 'content')
    at selectBlock (/Users/chiuhuilee/Documents/GitHub/3dw20240705auto20-next/node_modules/vue-loader/dist/select.js:23:45)
    at Object.loader (/Users/chiuhuilee/Documents/GitHub/3dw20240705auto20-next/node_modules/vue-loader/dist/index.js:93:41)
 @ ./src/components/Login.vue?vue&type=script&lang=js 1:0-197 1:0-197 1:198-384 1:198-384
 @ ./src/components/Login.vue 2:0-56 3:0-51 3:0-51 8:49-55
 @ ./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/App.vue?vue&type=script&lang=ts 9:0-43 36:4-9
 @ ./src/App.vue?vue&type=script&lang=ts 1:0-224 1:0-224 1:225-438 1:225-438
 @ ./src/App.vue 2:0-54 3:0-49 3:0-49 8:49-55
 @ ./src/main.ts 2:0-28 21:22-25

ERROR in ./src/components/Login.vue?vue&type=template&id=ef68022e&scoped=true&lang=pug (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[4]!./node_modules/pug-plain-loader/index.js!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/Login.vue?vue&type=template&id=ef68022e&scoped=true&lang=pug)
Module Error (from ./node_modules/vue-loader/dist/templateLoader.js):
[vue/compiler-sfc] Unexpected token, expected ")" (27:109)

/Users/chiuhuilee/Documents/GitHub/3dw20240705auto20-next/src/components/Login.vue
70 |        var autoredirect = true;
71 |  
72 |        if (this.$route.path === '/friends' || this.$route.path === '/maps' || $route.path.startsWith('/flag') {
   |                                                                                                               ^
73 |          autoredirect = false;
74 |        }
 @ ./src/components/Login.vue?vue&type=template&id=ef68022e&scoped=true&lang=pug 1:0-332 1:0-332
 @ ./src/components/Login.vue 1:0-87 8:68-74 18:86-20:3 19:29-35 18:2-20:4
 @ ./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/App.vue?vue&type=script&lang=ts 9:0-43 36:4-9
 @ ./src/App.vue?vue&type=script&lang=ts 1:0-224 1:0-224 1:225-438 1:225-438
 @ ./src/App.vue 2:0-54 3:0-49 3:0-49 8:49-55
 @ ./src/main.ts 2:0-28 21:22-25

ERROR in [eslint] 
/Users/chiuhuilee/Documents/GitHub/3dw20240705auto20-next/src/components/Login.vue
  72:109  error  Parsing error: ')' expected

✖ 1 problem (1 error, 0 warnings)


webpack compiled with 4 errors
No issues found.

**Comment by bestian** [comment]
剛才修好了~

**Comment by bestian** [comment]
well done

**Comment by leechiuhui** [comment]
不在電腦前，剛剛用手機測出兩個登入login問題：

1:手機📱不論是用google chrome 還是safari，在登入後,中間還會再次快閃一次登入畫面，請看https://www.loom.com/share/01e35a52e66e48279af45283ef7faaf0


2:手機📱google chrome在全新開啟視窗，且第一次登入we.alearn.org.tw，測了幾次都會出現如下圖錯誤訊息![image](https://github.com/user-attachments/assets/53d311d2-3941-465a-9f62-e3ec6c85a409)

🌹🙏

**Comment by bestian** [comment]
Unable to process request due to missing initial state.
This may happen if browser sessionStorage is inaccessible or accidentally cleared. Some specific scenarios are - 1) Using IDP-Initiated SAML SSO. 2)
Using signInWithRedirect in a storage-partitioned browser environment.

**Comment by bestian** [comment]
bug fixed.

**Comment by leechiuhui** [comment]
在機場無電腦，用手機📱google chrome 測試有bug,一直無法登入。請看：https://www.loom.com/share/44028d17774444be8579c4255f99a46a

**Comment by leechiuhui** [comment]
清除瀏覽資料和重開新無痕模式再連結🔗，就正常了。
