### ISSUE TITLE
try to put Riv animation on HomeView.vue but failed ..

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#173]
只是測試，不急

<img width="1491" alt="截圖 2024-09-06 下午5 37 30" src="https://github.com/user-attachments/assets/1771687f-62fa-4fb2-b063-6279d57472c6">

Please review the [commits](https://github.com/3dw/auto20-next/commit/d67e407b75c93a287f3cc226992bbb6a1ba110db) on HomeView.vue and /src/components/RiveComponent.vue when convenient, no rush..

**Comment by leechiuhui** [comment]
<img width="1512" alt="截圖 2024-09-06 晚上9 30 05" src="https://github.com/user-attachments/assets/f49939d8-dc97-4a38-a5ca-96ab42aa32a3">

**Comment by bestian** [comment]
@leechiuhui 
首頁沒問題，可是路由一切換就出bug了~
我對rive的導入完全沒概念，不知從何修改

<img width="1286" alt="自學2_0" src="https://github.com/user-attachments/assets/86203939-2239-4dfa-b922-36e439742ac0">

**Comment by leechiuhui** [comment]
喔喔，抱歉，沒測到登入後的情況。⋯，今天學校直播開課中，我要晚上才有時間將HomeView.vue恢復到原來前一日的版本。🙇‍♀️

**Comment by bestian** [comment]
不及，目前使用者端應該是看不出問題

**Comment by leechiuhui** [comment]
@bestian 謝謝老師。今天仍有直播工作，無法進一步測試，但簡單記錄一下：

- [ ] **### Question疑問:**

1. Hash mode 和 history mode的差別？
2. 什麼是惰性載入？
3. 為何改成惰性載入就ok了？
4. 之前的component: () => import(/* webpackChunkName: "about" */ '../views/FriendsView.vue')已經是惰性載入了？為何之前HomeView沒有惰性載入？


- [ ] ### **前天發現 Rive好像沒有Vue的支援，只有React**

1. 參照https://help.rive.app/runtimes/overview/vue
Currently, there is no official Rive "Vue"-specific runtime available, however, you can utilize the Web runtime packages in your Vue applications. Check out [this example](https://github.com/Coded-Clouds/Rive_Vue_ExampleApp)（https://github.com/Coded-Clouds/Rive_Vue_ExampleApp） from the community.

2. 詢問ChatGPT如何做 https://chatgpt.com/c/d01d0598-a5eb-4dfa-bc8b-c22fb51a9094
改動了vue.config.js   HomeView.vue 
新增RiveComponent.vue
安裝 Rive SDK 
yarn add rive-js
yarn add file-loader --dev
3. ### **但不work**




- [ ] ### **看到：https://stackoverflow.com/questions/71006532/rive-animation-in-vue-js-use-riv-file-from-assets 和
https://morty.tw/js-4-rive  發現可能只需更改成目前的 HomeView.vue ，就可以show出Rive的動畫，不需要 vue.config.js  和 RiveComponent.vue** 需要再進一步測試



- **其他Rive Vue參考：**

https://github.com/flowreaction/rive-vue
https://codesandbox.io/p/sandbox/vue-rive-example-sqpbts
https://morty.tw/js-4-rive
https://rivevue.netlify.app/#/
https://rive.app/community/forums/feature-requests/fsyCzA4A9Yar/vue-support/ftlsNuUFUt0E
Vue Support
It's unusual to see a tool geared towards the web which eschews Vue support. While Vue may not be quite as popular as React, it is still widely used, and offering support (be it a simple wrapper, or something more) would go a long way for the community. It would be great to see this offered as a feature in the future. 很少看到一個面向Web的工具避開了對 Vue 的支援。雖然 Vue 可能不像 React 那樣流行，但它仍然被廣泛使用，並且提供支援（無論是簡單的包裝器，還是其他東西）對社區大有説明。如果將來能看到此功能作為一項功能提供，那就太好了。
<img width="929" alt="截圖 2024-09-08 上午8 04 02" src="https://github.com/user-attachments/assets/03da3f08-56b1-4e1b-9ca5-8b126471ce6e">

**Comment by bestian** [comment]
@leechiuhui 

> @bestian 謝謝老師。今天仍有直播工作，無法進一步測試，但簡單記錄一下：
> 
> * [ ]  **### Question疑問:**
> 
> 1. Hash mode 和 history mode的差別？
<img width="1286" alt="自學2_0" src="https://github.com/user-attachments/assets/522ecb3e-ffa7-459c-91a7-66b329c48fb5">

> 2. 什麼是惰性載入？

惰性載入就是等到路由切換到某頁, 例如maps, 才會從router/index 載入maps的對應組件，這樣可以加速初始化並且避免一些問題 

> 3. 為何改成惰性載入就ok了？

就我所以，應該是HomeView要求有一個canvas主體來初始化Rive, 但在別的路由對應的組件並沒有一個canvas在template中，App.vue中也沒有，所以在別的路由啟動時，不要載入HomeView才對

> 4. 之前的component: () => import(/* webpackChunkName: "about" */ '../views/FriendsView.vue')已經是惰性載入了？為何之前HomeView沒有惰性載入？

用Vue Cli初始一個Vue專案時，它的Default是用"及早求值"的方式來載入HomeView。
這也合理，因為首頁會最先顯示，"及早求值"會快一點點

note: 可以用英文關鍵字查eager evaluation vs lazy evalution找到更多

**Comment by leechiuhui** [comment]
懂了，謝謝老師以上清楚回覆有關：何謂惰性載入和及早求值(eager evaluation vs lazy evalution)。
