### ISSUE TITLE
要如何Revert？

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#175]
@bestian 老師，請問要如何做revert? 如圖，謝謝～

<img width="1498" alt="截圖 2024-09-09 下午4 59 22" src="https://github.com/user-attachments/assets/c259f809-bb82-4946-92e5-b671d54e61d8">

**Comment by bestian** [comment]
在GitHub desktop 選history 
用右鍵點擊要倒退的commit 
他就會彈出一個選單，裡面有一項就是revert this commit

**Comment by leechiuhui** [comment]
感謝老師回覆。鞠躬～
