### ISSUE TITLE
給新手的任務清單

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#176]
發現新手住住升了旗就不知道還可以做什麼

建議在App.vue裡顯示一個新的component, 是login之後才會存在的
提示新手做4件事，每做完一件事就會自動打勾和跑條，打勾完和跑條跑滿，就出現按鈕可以隱藏這個component。

Tutorial.vue

- [x] 升起互助旗            >  可用users[uid] && users[uid].name 是否存在來確認
- [x] 將一位夥伴加入名簿    > 可用book && book[0] 是否存在來確認
- [x] 加入或創建一個社團     > 可用遍歷groups的members找對應的uid是否存在來確認
- [x] 在社團中推薦或建立一個資源   >  可用 #177 的資料來確認

**Comment by leechiuhui** [comment]
**### 完成任務1 升起互助旗**
<img width="1504" alt="截圖 2024-09-10 下午2 59 43" src="https://github.com/user-attachments/assets/df12b9c7-c0a1-41ec-b364-8f3985e22733">
<img width="1500" alt="截圖 2024-09-10 下午3 00 12" src="https://github.com/user-attachments/assets/7711eb6b-3993-4bb0-99fe-ea629fde35d0">

**Comment by bestian** [comment]
突然想到，為了要避免每次載入元件的時候都把所有資料包含社團資料也都摘錄一遍，可能可以讓使用者的資料裡面存起來allTaskComplete這個布爾值，如果他是假的的話提示元件根本就讓他不要載入

**Comment by leechiuhui** [comment]
> 為了要避免每次載入Tutorial 元件的時候都把所有資料包含社團資料也都載入一遍，
> 
> 可以讓使用者的資料裡面存起來

謝謝老師，我昨天是靠ChatGPT和剛好之前您教的issue #162 login providerdata花2小時亂湊實驗成功的，嘿嘿😁

目前在外無電腦，但想先請問這裡說的「存在裡面」是指怎麼存？因為我昨天也在想，每個程式都要載入一遍使用者資料的程式碼（如下圖）!

[image](https://github.com/user-attachments/assets/bb4a1e51-9ab9-4042-ae61-ca108caa45cd)

這樣程式會不會可能會被我搞的很亂很龐大⋯⋯⋯
猜想：若要改善，是不是用issue #168 老師您要做的這個component可以改善呢？？

另接下來兩週要完成40隻影片剪輯和空中飛行，會繼續用原子時間研究⋯⋯🌹～


allTaskComplete這個布爾值，如果他是假的的話提示元件根本就讓他不要載入

**Comment by bestian** [comment]
> > 為了要避免每次載入Tutorial 元件的時候都把所有資料包含社團資料也都載入一遍，
> > 可以讓使用者的資料裡面存起來
> 
> 謝謝老師，我昨天是靠ChatGPT和剛好之前您教的issue #162 login providerdata花2小時亂湊實驗成功的，嘿嘿😁
> 
> 目前在外無電腦，但想先請問這裡說的「存在裡面」是指怎麼存？因為我昨天也在想，每個程式都要載入一遍使用者資料的程式碼（如下圖）!
> 
> [image](https://github.com/user-attachments/assets/bb4a1e51-9ab9-4042-ae61-ca108caa45cd)
> 
> 這樣程式會不會可能會被我搞的很亂很龐大⋯⋯⋯ 猜想：若要改善，是不是用issue #168 老師您要做的這個component可以改善呢？？

#168和這個#176的元件最好是獨立開來的，互不影響。

> 
> 另接下來兩週要完成40隻影片剪輯和空中飛行，會繼續用原子時間研究⋯⋯🌹～
> 
> allTaskComplete這個布爾值，如果他是假的的話提示元件根本就讓他不要載入

這陣子也只有原子時間，剛剛修改了程式碼的地基，基本上是可以化簡得比較單純。(不好意思把你原本的程式碼砍了很多)


不過還沒時間測試跑起來如何？如果你那邊測試功能ok就可以再美化一下版型，再close this issue~感謝~

**Comment by leechiuhui** [comment]
**Bug1:升起互助旗幟後，進度條不會立即變更。
Bug2：刪除互助旗幟後，進度條不會立即變更。**

**Comment by leechiuhui** [comment]
修改 #176 進度條風格
<img width="645" alt="截圖 2024-09-12 下午5 47 15" src="https://github.com/user-attachments/assets/e149d40c-9790-49e1-8141-3af2a28c999c">

**Comment by leechiuhui** [comment]
@bestian  老～～師～～～我剛上面這個[進度條風格](https://github.com/3dw/auto20-next/commit/6d7fea15464910c5e9fc136a118d8a8cdaf367ff) 使用yarn build 和 push build後的程式碼，已經十五分鐘了，不知為何沒有看到新效果~~~

**Comment by bestian** [comment]
@leechiuhui 
我在
https://we.alearn.org.tw
上有看到效果~

應該是那時我還沒有fetch到你的新進度，我這邊也push了東西的關係

by the way, 新風格很漂亮但是height太高了, 會讓下面的router-view頁面被壓得太下面，可否用css改低一些?

**Comment by leechiuhui** [comment]
Height有調低一點，新風格使喚ChatGpt做的～^o^
<img width="499" alt="截圖 2024-09-12 下午6 41 46" src="https://github.com/user-attachments/assets/4e0eee5f-2cd5-4d11-ba0b-d65dd2ce0707">

但是可能不知道算不算是需要調整的邏輯：就是當 任務1:user互助旗幟還沒升起的時候，是不能執行"**任務3:加入新社團**"，但是使用者此前已經有“任務4:新增社團資源”和“任務2:名簿”紀錄都還存在（如上圖）。

**Comment by bestian** [comment]
把Logic改了一下, 後三個任務都要在第一個任務完成後才能點入, 也才會計算.

**Comment by bestian** [comment]
well done
