### ISSUE TITLE
新增Email Login功能

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#180]
- [x] 新增email sign up & email login，讓使用者可以用email驗證login，不一定要用google [Firebase email login 技術文檔](https://firebase.google.com/docs/auth/web/password-auth?hl=zh-tw)
- [x] Email認證功能 
- [x] TODO:   要讓未認證者不可以操作升旗動作
- [x] 新增forget password的功能  >.  https://firebase.google.com/docs/auth/web/manage-users?hl=zh-tw#send_a_password_reset_email

**Comment by leechiuhui** [comment]
@bestian  **### 老師好，想試著實驗研究處理這個issue，暫時產生以下三個可能很白目的問題請教😬（不著急，有空再回覆即可）：**

<img width="1498" alt="截圖 2024-09-15 下午2 17 41" src="https://github.com/user-attachments/assets/f928a61b-2907-4d13-a7fa-2b71c24eefc0">

目前最新的[commits][https://github.com/3dw/auto20-next/commit/c60aa9c43c0ebfdcaa3570489ec57310e57b7e6a](https://github.com/3dw/auto20-next/commit/c60aa9c43c0ebfdcaa3570489ec57310e57b7e6a)

出現的錯誤訊息如上圖。

**問題1. 想請問老師上面錯誤訊息，是否意味著需要去修改firebase的規則使其可以createUser呢,如下圖gemini的回覆？**

<img width="738" alt="截圖 2024-09-15 下午2 54 48" src="https://github.com/user-attachments/assets/73a8d078-61c8-473a-8315-ebb51041bccc">


**問題2. 若問題1的答案是要修改firebase的規則，目前firebase規則如下圖，是否是增加一行規則write": "auth != null" 在users下呢？**

<img width="1320" alt="截圖 2024-09-15 下午2 28 43" src="https://github.com/user-attachments/assets/fbe2e21d-f059-43a3-a79f-965137ff1437">




**問題3. 但是在想：若現在要用不是 google 的 email 來新增user createUser，但是卻沒有google account 提供的永遠不變的唯一值uid ，不知是否是要用random產生uid？但是若random產生uid的話，這樣在使用者刪除旗幟後，下次產生的uid就不一樣了.....這樣該使用者刪除旗幟前做好的名簿＆社團資料&...當以後他再升起旗幟後就不能match到了...**

**Comment by bestian** [comment]
@leechiuhui 

不用修改Firebase Security rules 

但是要在Auth項目下把email登錄打開

目前預設是沒有打開，我留著讓您試著打開並設定

![image](https://github.com/user-attachments/assets/ff8500bd-f78a-48db-ae0a-e8d2250ff2bc)


Firebase system will give an unique uid for each user，就像Google login 一樣

我們還要在Firebase設定若User 的Google Login email and Email login email are same, 就整合為同一個帳號。

**Comment by leechiuhui** [comment]
![image](https://github.com/user-attachments/assets/ab28731d-70f4-4405-815b-a381295ae92e)

開啟了。目前已可新增非Google email帳號，但登入後有bug,待處理。

**Comment by leechiuhui** [comment]
**非Google email帳號，但登入後的error messgae**


---
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at eval (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/ProfileView.vue?vue&type=script&lang=js:134:39)
<img width="1503" alt="截圖 2024-09-15 晚上9 58 11" src="https://github.com/user-attachments/assets/63dc20f5-1255-49be-bc7c-36a4f734e97a">

**Comment by bestian** [comment]
@leechiuhui 
email登入後傳回來的使用者資料，和Google登錄傳回來的使用者資料不一樣

console（user）可以看到他們的差異

所以我們可能需要在email登錄的時候手動建立可以對應的provider data 串列

**Comment by leechiuhui** [comment]
⚠️ATTENTION ⚠️ATTENTION ⚠️ATTENTION: Pink energy detected and has entered the area.
![image](https://github.com/user-attachments/assets/41af5b0c-e85a-41fb-813a-6ccad1b19aef)

**Comment by bestian** [comment]
@leechiuhui 
It’s ok. I invited @audreyt as outside collaborator to auto20-next to make help for solve the code’s complexity as tofus wang in free math to make new UI designs.

She’ll silently review our commitments, probably solve some issues if she wants and have time for this Project.

Welcome @audreyt.

**Comment by leechiuhui** [comment]
Welcome, @audreyt  (Cue the confetti!) 🎉

**Comment by leechiuhui** [comment]
**### 目前簡單測試報告：測試用的外部使用者帳號：wt_judylee@yahoo.com 密碼：testtest**

- [ ] **Bug1:wt_judylee@yahoo.com第一次登入就顯示已經是「升起旗幟」（尚未編寫profile也未升起旗幟）**

<img width="1475" alt="截圖 2024-09-16 下午5 47 03" src="https://github.com/user-attachments/assets/5bc5eb95-f82b-49fa-9471-0efd760aa324">

- [ ] **Bug2:email 已經認證過了，但還是顯示尚未驗證email**

<img width="1372" alt="截圖 2024-09-16 下午5 46 55" src="https://github.com/user-attachments/assets/c6881786-ff17-4329-ad81-5b7a5f59a54b">
<img width="1201" alt="截圖 2024-09-16 下午4 59 44" src="https://github.com/user-attachments/assets/90a4d41d-2c1b-477b-863a-40924368dc0c">

- [ ] **Bug3:使用者已經退出所有社團了，目前仍能顯示已推薦社團資源**

<img width="510" alt="截圖 2024-09-16 下午6 41 29" src="https://github.com/user-attachments/assets/1520c914-f5b7-4ff1-81be-bf49b39bcba0">

- [ ] **新增各種「登入」錯誤訊息，目前只有下面這種錯誤訊息**

<img width="475" alt="截圖 2024-09-16 晚上7 12 19" src="https://github.com/user-attachments/assets/e08a5efa-b6bf-4db3-8045-5a860871ef69">

**持續更新中............**

**Comment by bestian** [comment]
bug 3不是bug, 使用者退出社團不影響他推過的資源
其他bug已修復
