### ISSUE TITLE
處理相同的email帳號同時用兩種方法登入的問題

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#192]
- [x] 在email註冊時偵測是否已有相同email的google帳號，有的話就自動整合
- [x] 在Google Login時偵測是否有已有相同email的帳號且沒有創建google login的uid的user，有的話，若然就自動整合
- [ ] 修正不正確的畫面

技術文檔：

https://support.google.com/firebase/answer/9134820

https://chatgpt.com/share/66e8f81c-84a4-800b-9ed1-0d515818d8cc

**Comment by leechiuhui** [comment]
目前這個 commites ad17537，有大問題
用同樣的gmail,無法整合，如下圖，變成兩個 右邊的是用google login的，左邊的是用email login的...

<img width="1227" alt="截圖 2024-09-17 晚上8 06 52" src="https://github.com/user-attachments/assets/0db2028e-266b-4245-9ce0-c3254ab383f5">

**Comment by leechiuhui** [comment]
可是用另外一個coachsunshinelee@gmail.com卻可以
用email 註冊coachsunshinelee@gmail.com，進去後就是同一個帳號
<img width="1475" alt="截圖 2024-09-17 晚上8 10 47" src="https://github.com/user-attachments/assets/6f61227e-bbf6-4442-9973-36ecca6db387">

**Comment by bestian** [comment]
@leechiuhui 
i know, 正在修, 你先去睡吧...這bug不急

我有點擔心你太投入

我有問了一下GPT, 
有躁症體質的軟體工程師如何避免過度投入引起躁症

https://chatgpt.com/share/66e9d44a-c158-800b-a182-3511436adc1d

**Comment by bestian** [comment]
現在雙向都可以整合了，但是在email login轉google login時會有短暫的瞬間，出現不正確的畫面。
