### ISSUE TITLE
非google email註冊－》email認證完畢->進入旗幟“編輯”時，出現錯誤訊息

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#201]
<img width="471" alt="截圖 2024-09-17 下午3 26 38" src="https://github.com/user-attachments/assets/d68d7336-b7c2-466e-98f8-32b9a63d1bf4">

Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at Proxy.initMap (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/ProfileView.vue?vue&type=script&lang=js:90:97)

**Comment by leechiuhui** [comment]
用cursor改好了^o^，這樣可以退訂github copilot +chatgpt +gemini了～～～
感謝天感謝地 感謝 @audreyt 感謝  ～@bestian 老師～

**Comment by bestian** [comment]
> 用cursor改好了^o^，這樣可以退訂github copilot +chatgpt +gemini了～～～ 感謝天感謝地 感謝 @audreyt 感謝 ～@bestian 老師～

@leechiuhui
cursor應該是可以取代copiot, gemini
不過chatGPT最近有出o1, o1-mini具有深思、架構分析的能力

可以搭配cusor來處理多檔案的架構分析。
cusor在處理多檔案架構分析時，選用o1-mini的效果應該是比內附的AI還好。

所以chatGPT建議先不急著退。 :)

https://openai.com/index/introducing-openai-o1-preview/

**Comment by leechiuhui** [comment]
謝謝老師。剛剛最後就是改用ChatGPT才可以，不知為何cursor突然不行,哈哈。

另現在才知道原來要用o1-Mini不是用o1-preview.因為這幾天我用o1-preview覺得它反應超慢，4o還比較好跟快。

我剛興奮地連續4小時（使喚）cursor&chatgpt coding了，#192應該是有bug或是邏輯不對，我（使喚）腦汁用完了先休息一下⋯⋯🫡 

P.s.gemini確實不太OK～
