### ISSUE TITLE
社團留言框可以改成textarea

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#213]
讓他大一點，目前有點太小，沒辦法打很多字

**Comment by leechiuhui** [comment]
The "Leave a message" section has been changed to a textarea as shown in the image, but I have one question: Where can I delete the messages on Firebase? Currently, I can't seem to find the option. Apologies for the inconvenience!

<img width="838" alt="截圖 2024-10-09 晚上8 49 07" src="https://github.com/user-attachments/assets/298fdc42-af5c-47f8-83e1-38051b29fd8d">

**Comment by bestian** [comment]
@leechiuhui 
用電腦，登入Firebase console後，選realtime database，點開巢狀結構到你想要刪掉的測試留言位置。
用滑鼠滑上去之後，右邊會浮出"垃圾筒"的圖示，點擊即可刪除。
