### ISSUE TITLE
加入「意見回饋」google form

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#214]
- [x] Create [google form ](https://docs.google.com/forms/d/1_KpVjHe7yv96sXei5ZWzhKiBK6LBWBV4is7RbiVHIas/edit)
- [x] Embed it to a new view page
- [x] Add link on Footer

**Comment by bestian** [comment]
@leechiuhui 可以幫忙看一下新開的[Google Form](https://docs.google.com/forms/d/1_KpVjHe7yv96sXei5ZWzhKiBK6LBWBV4is7RbiVHIas/edit)內容和署名是否ok嗎? 謝謝~

**Comment by leechiuhui** [comment]
@Bestian 老師，我已經閱讀完內容，並直接進行了修改，請您查閱。

**Comment by bestian** [comment]
> @bestian 老師，我已經閱讀完內容，並直接進行了修改，請您查閱。

@leechiuhui 哇，不謹文字完善化、問答精簡化、還加入了圖，真是wounderful~

**Comment by bestian** [comment]
有個小點

1. 我願意加入[https://github.com/3dw](https://www.google.com/url?q=https://github.com/3dw&sa=D&source=editors&ust=1727950867337362&usg=

這一項需要有人引介，加入正式促進會會員才行。

是否

3. 我會網頁設計和程式開發 (HTML, CSS 等)，我想加入資訊志工團參與協作

中的"資訊志工團"包含會外協作者，只要有Github帳號和良善工作倫理即可(如@audreyt  或 @tofuswang)呢? 如果是這個意思的話，應該比較有機會招到人。有些人願意協作但不想入會，或是沒有人引介入會。

**Comment by leechiuhui** [comment]
> 有個小點
> 
> 1. 我願意加入[https://github.com/3dw](https://www.google.com/url?q=https://github.com/3dw&sa=D&source=editors&ust=1727950867337362&usg=
> 
> 這一項需要有人引介，加入正式促進會會員才行。
> 
> 是否
> 
> 3. 我會網頁設計和程式開發 (HTML, CSS 等)，我想加入資訊志工團參與協作
> 
> 中的"資訊志工團"包含會外協作者，只要有Github帳號和良善工作倫理即可(如@audreyt 或 @Tofuswang)呢? 如果是這個意思的話，應該比較有機會招到人。有些人願意協作但不想入會，或是沒有人引介入會。

@bestian @jennywilkins 
如果改成下圖這樣呢？
<img width="662" alt="截圖 2024-10-03 下午5 52 59" src="https://github.com/user-attachments/assets/16f0e5e0-c580-4e66-b9c6-214ae2008e35">

**Comment by bestian** [comment]
I think the new version is pretty good.
