### ISSUE TITLE
加入CloudFlare Turnstile以防止偽帳號及機器人登入

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#218]
https://blog.cloudflare.com/zh-tw/turnstile-ga-zh-tw

**Comment by bestian** [comment]
@leechiuhui 

我做到一半卡住了，

先

1. 建立了一隻Turnstiles在Alearn13994229@gmail.com的CloudFlare帳號中
2. 建立了一隻worker
3. 開了worker協作權限邀約給您
4. 建立了 https://github.com/3dw/turnstile-demo-workers

不急，有空時麻煩再接力~

**Comment by bestian** [comment]
@audreyt 
事實上，我還不確定我目前設定的方向對不對。因為我們的login是用firebase auth, 要整合Turnstiles的橋階邏輯我還沒有完全搞懂. 有空時可以示範指導一下嗎？謝謝!

**Comment by leechiuhui** [comment]
@bestian 老師，我先用Firebase Cloud Functions的方向來試試看...



請問上面這句話「請注意，您需要在後端添加一個新的 API 端點來驗證 Turnstile token。這個端點應該向 Cloudflare 的驗證 API 發送請求。」，請問這個後端是指在哪裡？

----------

非常抱歉之前沒有解釋清楚。這個"後端"指的是您的服務器端應用程序，它處理來自前端的請求並與數據庫交互。在您的情況下，這可能是一個 Node.js 服務器，或者是您用來處理 API 請求的任何其他服務器端技術。

根據您之前提供的代碼，我沒有看到明確的後端代碼。通常，在 Vue.js 應用中，後端可能是：

1. 一個獨立的 Node.js 服務器（例如使用 Express.js）
2. 一個無服務器函數（例如 Firebase Cloud Functions）
3. 任何其他能夠處理 HTTP 請求的服務器端技術

在您的情況下，由於您使用了 Firebase，您可以考慮使用 Firebase Cloud Functions 來創建這個驗證端點。以下是如何使用 Firebase Cloud Functions 創建這個端點的示例：

1. 首先，確保您已經安裝了 Firebase CLI 並初始化了 Firebase 項目。

2. 在您的項目根目錄中，創建一個新的 `functions` 目錄（如果還沒有的話）。

3. 在 `functions` 目錄中，創建一個 `index.js` 文件（如果還沒有的話），並添加以下代碼：

```javascript
const functions = require('firebase-functions');
const axios = require('axios');

exports.verifyTurnstile = functions.https.onCall(async (data, context) => {
  const { token } = data;
  const secretKey = 'YOUR_CLOUDFLARE_SECRET_KEY';

  try {
    const response = await axios.post(
      'https://challenges.cloudflare.com/turnstile/v0/siteverify',
      `secret=${secretKey}&response=${token}`,
      {
        headers: {
          'content-type': 'application/x-www-form-urlencoded',
        },
      }
    );

    return { success: response.data.success };
  } catch (error) {
    console.error('Turnstile verification error:', error);
    throw new functions.https.HttpsError('internal', 'Turnstile verification failed');
  }
});
```

4. 在 `functions` 目錄中運行 `npm install axios` 來安裝必要的依賴。

5. 部署您的 Firebase 函數：在項目根目錄運行 `firebase deploy --only functions`。

然後，在您的 Vue.js 應用程序中，您需要修改 `verifyTurnstileToken` 方法來調用這個 Cloud Function：

```javascript
import { getFunctions, httpsCallable } from 'firebase/functions';

// ...

methods: {
  async verifyTurnstileToken(token) {
    const functions = getFunctions();
    const verifyTurnstile = httpsCallable(functions, 'verifyTurnstile');
    try {
      const result = await verifyTurnstile({ token });
      return result.data.success;
    } catch (error) {
      console.error("Turnstile 驗證錯誤", error);
      return false;
    }
  },
  // ...
}
```

這樣，您就創建了一個安全的後端端點來驗證 Turnstile token，而不需要設置單獨的服務器。Firebase Cloud Functions 將處理驗證請求，保護您的 Cloudflare 密鑰不被暴露給前端。

記得將 `YOUR_CLOUDFLARE_SECRET_KEY` 替換為您實際的 Cloudflare secret key。

**Comment by bestian** [comment]
@leechiuhui 我剛剛把v-if改成v-show之後，好像成功了~
似乎只剩style要調整?

**Comment by bestian** [comment]
> @bestian 老師，我先用Firebase Cloud Functions的方向來試試看...
> 
> 請問上面這句話「請注意，您需要在後端添加一個新的 API 端點來驗證 Turnstile token。這個端點應該向 Cloudflare 的驗證 API 發送請求。」，請問這個後端是指在哪裡？
> 
> 非常抱歉之前沒有解釋清楚。這個"後端"指的是您的服務器端應用程序，它處理來自前端的請求並與數據庫交互。在您的情況下，這可能是一個 Node.js 服務器，或者是您用來處理 API 請求的任何其他服務器端技術。
> 
> 根據您之前提供的代碼，我沒有看到明確的後端代碼。通常，在 Vue.js 應用中，後端可能是：
> 
> 1. 一個獨立的 Node.js 服務器（例如使用 Express.js）
> 2. 一個無服務器函數（例如 Firebase Cloud Functions）
> 3. 任何其他能夠處理 HTTP 請求的服務器端技術
> 
> 在您的情況下，由於您使用了 Firebase，您可以考慮使用 Firebase Cloud Functions 來創建這個驗證端點。以下是如何使用 Firebase Cloud Functions 創建這個端點的示例：
> 
> 1. 首先，確保您已經安裝了 Firebase CLI 並初始化了 Firebase 項目。
> 2. 在您的項目根目錄中，創建一個新的 `functions` 目錄（如果還沒有的話）。
> 3. 在 `functions` 目錄中，創建一個 `index.js` 文件（如果還沒有的話），並添加以下代碼：
> 
> ```js
> const functions = require('firebase-functions');
> const axios = require('axios');
> 
> exports.verifyTurnstile = functions.https.onCall(async (data, context) => {
>   const { token } = data;
>   const secretKey = 'YOUR_CLOUDFLARE_SECRET_KEY';
> 
>   try {
>     const response = await axios.post(
>       'https://challenges.cloudflare.com/turnstile/v0/siteverify',
>       `secret=${secretKey}&response=${token}`,
>       {
>         headers: {
>           'content-type': 'application/x-www-form-urlencoded',
>         },
>       }
>     );
> 
>     return { success: response.data.success };
>   } catch (error) {
>     console.error('Turnstile verification error:', error);
>     throw new functions.https.HttpsError('internal', 'Turnstile verification failed');
>   }
> });
> ```
> 
> 4. 在 `functions` 目錄中運行 `npm install axios` 來安裝必要的依賴。
> 5. 部署您的 Firebase 函數：在項目根目錄運行 `firebase deploy --only functions`。
> 
> 然後，在您的 Vue.js 應用程序中，您需要修改 `verifyTurnstileToken` 方法來調用這個 Cloud Function：
> 
> ```js
> import { getFunctions, httpsCallable } from 'firebase/functions';
> 
> // ...
> 
> methods: {
>   async verifyTurnstileToken(token) {
>     const functions = getFunctions();
>     const verifyTurnstile = httpsCallable(functions, 'verifyTurnstile');
>     try {
>       const result = await verifyTurnstile({ token });
>       return result.data.success;
>     } catch (error) {
>       console.error("Turnstile 驗證錯誤", error);
>       return false;
>     }
>   },
>   // ...
> }
> ```
> 
> 這樣，您就創建了一個安全的後端端點來驗證 Turnstile token，而不需要設置單獨的服務器。Firebase Cloud Functions 將處理驗證請求，保護您的 Cloudflare 密鑰不被暴露給前端。
> 
> 記得將 `YOUR_CLOUDFLARE_SECRET_KEY` 替換為您實際的 Cloudflare secret key。

目前的後端是在CloudFlare Worker上，也有收到請求，所以應該是可行的，不需要Firebase Function?
<img width="1277" alt="Workers_和_Pages___Alearn13994229_gmail_com_s_Account___Cloudflare" src="https://github.com/user-attachments/assets/d3f99537-f756-48df-b672-a003b2077adc">

**Comment by bestian** [comment]
@leechiuhui 我這邊的畫面看起來看這樣，所以應該是成功了? (沒有用過有點不確定感...)

<img width="775" alt="自學2_0" src="https://github.com/user-attachments/assets/f71f14ba-71e6-4719-ab45-360181daa826">
<img width="354" alt="自學2_0_1" src="https://github.com/user-attachments/assets/dc16ae8f-3fa3-47c7-80fe-b701d1ccc02f">

**Comment by bestian** [comment]
非互動式的好像成功了，但是互動式出現勾取框時，一勾取就出以下error：

![IMG_3888](https://github.com/user-attachments/assets/75870c07-93b8-48cc-a5ba-c4e2842459ea)

**Comment by bestian** [comment]
<img width="656" alt="Turnstile___Alearn13994229_gmail_com_s_Account___Cloudflare" src="https://github.com/user-attachments/assets/bd1293ab-a596-4958-942d-a6635e46b81a">

改成"非互動式", 應該是完成了~

**Comment by leechiuhui** [comment]
@bestian 老師，目前程式似乎還無法正常運行，可能還有一些 bug。我剛剛使用現有的程式碼進行了一些測試，結果如下圖所示。不過，今天我就先撤退了～ 😄

其中，第二張圖顯示在 Login 處「出現了兩個 Cloudflare 驗證框」。

<img width="1397" alt="截圖 2024-10-04 下午5 46 18" src="https://github.com/user-attachments/assets/77d6bdda-3203-4dc9-a133-7587d88710e5">
<img width="1485" alt="截圖 2024-10-04 下午5 46 29" src="https://github.com/user-attachments/assets/c28811b4-1776-455d-b873-f6522796ee62">

**Comment by bestian** [comment]
我這邊上線測，chrome正常, safari會出現兩個, 先記下問題, 休息了~

**Comment by bestian** [comment]
目前重新build後，在https://we.alearn.org.tw上測試，一切正常。
