### ISSUE TITLE
確保PopUp不要被Safari擋住

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#219]
![image](https://github.com/user-attachments/assets/c1db9aaf-283a-4ebc-af52-be404b730e3c)

**Comment by bestian** [comment]
這是Safari的問題, 它會自動阻擋第一次的popup

**Comment by bestian** [comment]
可以試試看把signInWithPopUp改成signInWithRedirect，不過今天我的Energy也用完了，撤退了~

**Comment by bestian** [comment]
在 Firebase Google 認證中使用 `signInWithRedirect` 取代 `signInWithPopup` 會有一些利弊，以下是簡要比較：

### 優點：
1. **更好地處理手機瀏覽器：**
   - 在行動設備或部分受限制的瀏覽器中，`signInWithPopup` 可能無法正常工作，而 `signInWithRedirect` 在這些環境中表現較佳，因為它不依賴彈出窗口。

2. **較少彈出攔截問題：**
   - `signInWithPopup` 依賴瀏覽器彈出窗口，可能會被瀏覽器的彈出攔截功能阻擋，而 `signInWithRedirect` 是直接跳轉到 Google 認證頁面，較少受到這類攔截影響。

3. **支援更多環境：**
   - 某些環境（如 Electron 應用程序或內嵌 WebView）不支援彈出窗口，這時候 `signInWithRedirect` 是較好的選擇。

### 缺點：
1. **跳轉體驗較差：**
   - 使用 `signInWithRedirect` 會將用戶重定向到 Google 的認證頁面並在完成後跳回原頁面，這可能會中斷用戶體驗，特別是在單頁應用（SPA）中，可能會讓使用者感到不便。

2. **需要處理頁面重載：**
   - 當使用 `signInWithRedirect` 時，應用會重載或重新進入，因此你需要在頁面重新加載後正確處理結果，這會增加開發上的複雜度。

3. **彈性較低：**
   - 相較於 `signInWithPopup` 的即時彈窗回應，`signInWithRedirect` 的流程需要在頁面重新加載後才能處理認證結果，無法實現即時的用戶操作回應。

選擇哪種方法應根據應用程式的需求和使用者環境而定。

**Comment by bestian** [comment]
我查了一下Safari的限制，如果事件是立即觸發確定是使用者點擊按鈕而觸發，他就不會擋pop up

我感覺出錯的方向應該是先註解掉一部分的功能，例如自動重新導向，試試看能不能夠運作。

或是把setup的寫法，改為類似Vue2的寫法，有的時候這樣就會成功

**Comment by bestian** [comment]
@leechiuhui 

回顧我對這個議題偵測錯誤的過程，一開始的時候受到A I的影響，想試著把彈出視窗改成重導向登入，結果陷入了死胡同。

後來才警覺到Vue深層的單頁應用程式SPA會阻止重新載入，並不適合重導向登入。

看起來方向錯誤比細節錯誤是更大的問題。方向如果設定對了，其實細節處理起來比想像中的還要容易。
