### ISSUE TITLE
CloudFlare turnstile的連結有問題

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#220]
目前新用戶皆無法通過驗證

**Comment by bestian** [comment]
已重設後端程式碼並解決此問題~

**Comment by bestian** [comment]
@leechiuhui 等下週您有空時，可否再double check一次新用戶註冊時可以順利通過驗證並註冊呢? 

謝謝~

用過的測試帳號的Auth可以在Firebase後台的Authentication

部份先刪掉, 即可重覆使用~感謝

double check完再close this issue好了, 比較保險

**Comment by bestian** [comment]
@leechiuhui 回顧這個除錯的過程，
我發現傳統的除錯方式，也就是把資訊流延著程式碼去跑，設置斷點和縮小問題範圍，並密切注意console的錯誤訊息
再以chatGPT問答當輔助
還是有它的價值。

因為早上想用cursor AI一次解決卻一直卡住，原來後端和前端兩邊要一起動的時候，還是需要人的腦汁...

^_^

**Comment by leechiuhui** [comment]
> 已重設後端程式碼並解決此問題~
@bestian 
老師好,
我目前人在外面，無法在電腦前操作，但想先請教您一下（不急著回覆），這裡提到的「已重設後端程式碼並解決此問題」具體是指什麼呢？

因為我昨天下午在本地端按照 AI 的指示，遠端安裝了 Firebase CLI，似乎也進行了遠端登入 Firebase，和下了firebase --deploy 的一些命令⋯⋯不確定是否因為這樣，導致後端程式出了問題，所以您才需要重設後端程式碼。😅🥶

**Comment by leechiuhui** [comment]
> @leechiuhui 回顧這個除錯的過程，
> 
> 我發現傳統的除錯方式，也就是把資訊流延著程式碼去跑，設置斷點和縮小問題範圍，並密切注意console的錯誤訊息
> 
> 再以chatGPT問答當輔助
> 
> 還是有它的價值。
> 
> 
> 
> 因為早上想用cursor AI一次解決卻一直卡住，原來後端和前端兩邊要一起動的時候，還是需要人的腦汁...
> 
> 
> 
> ^_^

對啊！😁
剛剛留言完上則訊息，才看到您這則訊息。
其實我昨天晚上是有想應該是被我亂搞造成的⋯，😅
還好老師您腦汁今天夠用，辛苦您了。🍵🍵🍵

**Comment by bestian** [comment]
@leechiuhui Firebase function 那邊應該是還好，因為原本往後端的請求就沒有發送到forename function 上

今天開始debug的時候，他發送到的是空的位置

後來我把它接到促進會的cloudflare worker上，然後開始處理錯誤訊息，大概專注了一個小時左右才解決掉，最後的版本，可以在促進會的cloudflare worker 上面看到後端程式碼

大概是這樣，所以不必自責。

**Comment by bestian** [comment]
至於後端程式碼的部分，主要的調整是處理preflight request 和 跨域資源共享(CORS)相關的回應標頭設定

概念請GPT說明如下：
https://chatgpt.com/share/6700a6c1-4c20-800b-80f9-9b67bd5a01f8

程式碼因為涉及秘密金鑰，請直接到促進會的 cloudflare worker 上面去看，就不在這裡貼出了

**Comment by leechiuhui** [comment]
> 至於後端程式碼的部分，主要的調整是處理preflight request 和 跨域資源共享(CORS)相關的回應標頭設定
> 
> 
> 
> 概念請GPT說明如下：
> 
> https://chatgpt.com/share/6700a6c1-4c20-800b-80f9-9b67bd5a01f8
> 
> 
> 
> 程式碼因為涉及秘密金鑰，請直接到促進會的 cloudflare worker 上面去看，就不在這裡貼出了

感謝老師的回覆，我會晚點再仔細研讀。🫡

**Comment by leechiuhui** [comment]
> 至於後端程式碼的部分，主要的調整是處理preflight request 和 跨域資源共享(CORS)相關的回應標頭設定
> 
> 概念請GPT說明如下： https://chatgpt.com/share/6700a6c1-4c20-800b-80f9-9b67bd5a01f8
> 
> 程式碼因為涉及秘密金鑰，請直接到促進會的 cloudflare worker 上面去看，就不在這裡貼出了

@bestian 老師，不好意思打擾了～我在 Cloudflare 的 Worker 的 auto20-next 介面上找了很久（也詢問了 AI），但還是沒找到相關的程式碼。能麻煩您指點一下嗎？感謝您！😬💦 謝謝～🌻

**Comment by bestian** [comment]
進到那個worker裡頭，然後點選編輯代碼，之後左邊會有一個編輯器完整的後端程式碼，為了避免不小心修改到，可以把它複製到電腦上的一個空白文件裡慢慢看，謝謝。

![IMG_3917](https://github.com/user-attachments/assets/4ed80121-0838-4889-95b3-821a3bddd79a)

**Comment by leechiuhui** [comment]
> @leechiuhui 等下週您有空時，可否再double check一次新用戶註冊時可以順利通過驗證並註冊呢?
> 
> 謝謝~
> 
> 用過的測試帳號的Auth可以在Firebase後台的Authentication
> 
> 部份先刪掉, 即可重覆使用~感謝
> 
> double check完再close this issue好了, 比較保險

**在Firebase後台的Authentication將之前的測試帳號刪掉後的測試報告：**
註冊方向1:
從不是goolge login處註冊google帳號後，再點選[以Google 帳號登入]

和
註冊方向2:
從 [以Google 帳號登入]第一次註冊進入，再在下方用email address登入

兩個方向皆會將帳號整合，且在Firebase [後台Ａuth處觀看，會有兩個標誌。如下圖]
<img width="334" alt="截圖 2024-10-09 晚上7 15 13" src="https://github.com/user-attachments/assets/258e30d4-09f7-45a5-83e9-cefbb07a2c3a">

**Comment by leechiuhui** [comment]
已經完成✅測試
和
看到👀 Cloudflare 的 Worker中的turnstile的後端程式碼。
感謝。🙏
