### ISSUE TITLE
願望清單2:點選登入按鈕後系統會要求先玩一個小遊戲如畫一棵樹或踢毽子後，才讓使用者填寫帳號密碼

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#223]
請幫我為https://we.alearn.org.tw
企劃一個惡搞小機制：點選登入按鈕後系統會要求先玩一個小遊戲如畫一棵樹或踢毽子後，才讓使用者填寫帳號密碼

---------------------
這是一個非常有趣的惡搞機制！以下是具體的延伸與設計想法：

### 惡搞小機制設計：
1. **小遊戲啟動流程：**
   當使用者點選登入按鈕時，系統不會立即顯示帳號密碼的輸入框，而是彈出一個遊戲窗口，要求先完成一個簡單的小遊戲才能繼續登入。

2. **遊戲範例：**
   - **畫一棵樹**：使用 Canvas 讓使用者用滑鼠在一個虛擬畫布上畫出一棵簡單的樹，當系統偵測到足夠的畫筆軌跡（類似樹的形狀）時，才會解鎖登入頁面。
   - **踢毽子**：顯示一個簡單的 JavaScript 小遊戲，毽子從上方落下，使用者需要點擊或按下空白鍵讓毽子保持在空中，成功達到一定次數後才解鎖登入頁面。
   - **點擊小天使**：螢幕上會隨機出現一些「小天使」角色，使用者需要在限定時間內點擊足夠數量的小天使角色才可解鎖登入頁面。
   
3. **互動性與幽默感**：
   - **遊戲失敗懲罰**：如果使用者未能在遊戲中達到要求，例如踢毽子時毽子掉落，可以彈出幽默的提示，例如「再試一次，小天使需要你！」或者「你還未準備好登入！再挑戰一次吧！」
   - **隨機小遊戲**：每次點擊登入按鈕時，系統會隨機挑選一款不同的迷你遊戲，讓每次體驗都有些許不同，增加趣味性和變化。

4. **解鎖機制：**
   當使用者完成小遊戲後，系統會出現動畫效果，例如「小天使幫你打開大門！」，然後帳號密碼輸入框才會顯示，允許使用者進行正式登入。

5. **紀錄與分享**：
   - **排行榜或成就**：使用者可以在某些遊戲中獲得分數，這些分數可以累積成「惡搞成就」或出現在一個隱藏的排行榜中，讓玩家之間有一個輕鬆競爭的互動元素。
   - **社群分享**：完成遊戲後，系統可提供一個分享按鈕，讓使用者可以將自己完成的遊戲畫面或分數分享到社群媒體，吸引其他人參與登入挑戰。

這樣的機制能夠有效增加登入過程的趣味性，讓網站變得更加活潑有趣，同時也能與網站的「小天使」主題相呼應，增強整體的互動體驗。

**Comment by bestian** [comment]
的確有新意~

But I'm a little bit worry about this new feature.
用戶體驗可能會不好~因為登入速度變慢了
會不會因此就不登入而離開了?

建議要試的話先用A/B測試讓一半的用戶玩玩看，測一下流量
https://firebase.google.com/docs/ab-testing?hl=zh-tw

**Comment by leechiuhui** [comment]
> But I'm a little bit worry about this new feature.但我有點擔心這個新功能。 用戶體驗可能會不好~因為登入速度變慢了 會不會因此就不登入而離開了?

>>
對啊，這確實有可能！這個功能或許可以只在萬聖節期間啟動比較好😂
抱歉老師，昨天玩 Canvas 的時候不小心玩心大起，結果有點超過了......
另外，感謝老師告知這個測試工具！https://firebase.google.com/docs/ab-testing?hl=zh-tw
