### ISSUE TITLE
調整無此帳號的錯誤訊息，使其更白話文

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#229]
- [x] - 調整無此帳號的錯誤訊息，使其更白話文，目前如下圖
<img width="1278" alt="截圖 2024-10-09 晚上7 25 38" src="https://github.com/user-attachments/assets/988864e0-84f1-43e4-8ba6-625573ceb774">

**Comment by leechiuhui** [comment]
密碼錯誤也須白話文
<img width="686" alt="截圖 2024-10-16 下午6 13 07" src="https://github.com/user-attachments/assets/64a6cadd-12be-4a6a-817e-a32bba11ae48">
