### ISSUE TITLE
驗證信改良內容和署名?

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#230]
- [ ] 驗證信改良內容和署名
![image](https://github.com/user-attachments/assets/475f3609-a51d-414d-8a88-d6de5725d9c2)

**Comment by leechiuhui** [comment]
發現不能改內容，只改了Title為：歡迎加入【自學2.0】 請驗證您的電子郵件地址
如下截圖

<img width="670" alt="截圖 2024-10-16 下午5 33 51" src="https://github.com/user-attachments/assets/76b1009a-4248-4256-be45-369e28e5e2bf">
<img width="724" alt="截圖 2024-10-16 下午5 52 33" src="https://github.com/user-attachments/assets/e87b788c-a091-444c-8574-020f27b99e34">
