### ISSUE TITLE
［群聊］[地圖］[夥伴]等的登入不會提示「不能從fb app等登入」

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#235]
從Facebook連結auto2.0-next,首頁會提示要用瀏覽器登入，但是，［群聊］[地圖］[夥伴]等的登入不會提示「不能從fb app等登入」，會進入登入模式後幾頁才顯示無法登入。這個可能要想一下要怎麼處理⋯⋯是否［群聊］[地圖］[夥伴]等要顯現一些資訊，需要某些功能時才提示登入 之類的⋯⋯如島島阿學🤔

![image](https://github.com/user-attachments/assets/6a742fee-3853-4185-b40a-f10b1095598c)![image](https://github.com/user-attachments/assets/f96066f3-b9c1-4dda-80a0-bc7f54abf865)![image](https://github.com/user-attachments/assets/5cd23d52-bba3-4fbb-8d07-ad1d106efaea)![image](https://github.com/user-attachments/assets/4f6e82bf-1ce3-49f0-a5c0-fe39cdab88f4)

**Comment by bestian** [comment]
應該是改Login Compoent, 把提示的話語移到Login Compoent的醒目處顯示即可。
