### ISSUE TITLE
運用make串接功能開發Line自學問題問答機器人

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#25]
[Ｍake:](https://www.make.com/en?pc=homepage&gad_source=1&gclid=CjwKCAjwupGyBhBBEiwA0UcqaKs34GFLt2mngegTDl54_QJczJ1P9RWp7wFzsmSMOcQlaYLfChuX5hoCR4UQAvD_BwE) 
ChatGPT + Make 自動化解決方案(Line+Airtable+chatgpt api):很好用也很簡單串接，但是 line ,make ,Chatgpt Api都需要成本。
純提議，成本考量應該行不通，後天會自行close。

**Comment by leechiuhui** [comment]
![part of ppt](https://github.com/3dw/auto20-next/assets/107933615/58660fca-e462-4281-b287-31692f51636c)

**Comment by leechiuhui** [comment]
Hi,Teacher Tang,
Thank you for setting this issue as「點子集」，does it means that am I able to remain it not to close，right？
or should I close it first and until in the future I can find time to make it as prototype to be evaluated,no time limit,right?
Have a nice day.

**Comment by bestian** [comment]
我同意先close比較好✅
這樣想可以先專注在核心功能

**Comment by leechiuhui** [comment]
ＯＫ！Thanks Teacher Tang (TT)  for Reply.
