### ISSUE TITLE
資料庫獨立=>首頁顯示的使用者

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#33]
- [ ] 在Firebase上多一個publicUsers
- [ ] 在Profile Page更新或登錄時, 同步更新publicUsers

**Comment by leechiuhui** [comment]
Hello, teacher. As a member of 3DW, may I request the login credentials for Firebase to view the table?

**Comment by bestian** [comment]
> Hello, teacher. As a member of 3DW, may I request the login credentials for Firebase to view the table?

已開啟檢視資料庫權限, 系統應會寄邀請信, 請查收, 謝謝.

**Comment by leechiuhui** [comment]
Thank you, teacher. I will study it slowly in my free time.
