### ISSUE TITLE
聯絡方式如果是email的話，點擊時應該要可以發信

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#47]

**Comment by leechiuhui** [comment]
I might have successfully completed this issue with the help of GitHub Copilot. Now, it's waiting to be reviewed and merged. ^^

**Comment by bestian** [comment]
> I might have successfully completed this issue with the help of GitHub Copilot. Now, it's waiting to be reviewed and merged. ^^

Thanks a lot & 恭喜試驗成功~~

**Comment by leechiuhui** [comment]
Thank you, teacher, for the guidance.
