### ISSUE TITLE
Bug:（iOS Safari）使用者登入後會系統會將之連到先前進入過的網址。

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#68]
Bug:（iOS Safari）使用者登入後會系統會將之連到先前進入過的網址。推測可能跟近端儲存區儲存的資料（先前網址）有關。

**Comment by bestian** [comment]
@leechiuhui 是在PWA模式(安裝在主畫面的icon點入)還是Safari? iOS Safari上我這邊沒辦重現這個問題。

**Comment by leechiuhui** [comment]
https://github.com/3dw/auto20-next/assets/107933615/d9359220-f41d-4b24-8993-2e00ba024e5d

目前是如上影片，最後停在錯誤訊息，稍早是一直連到某個先前的網站。

**Comment by leechiuhui** [comment]
直接是Safari瀏覽器，不是PWA

**Comment by bestian** [comment]
先截取錯誤訊息

Unable to process request due to missing initial sta This may happen if browser sessionStorage is inaccessible or accidentally cleared. Some specific scenarios are - 1) Using IDP-Initiated SAML SSO. 2 Using signInWithRedirect in a storage-partitioned browser environment.

**Comment by bestian** [comment]
已新增錯誤提示

.catch((error) => {
          console.error("Login error:", error);
          if (error.message.includes('sessionStorage')) {
            window.alert('瀏覽器不支持sessionStorage，請檢查瀏覽器設置或更換瀏覽器再試一次。');
          }
        });

**Comment by bestian** [comment]
@leechiuhui 已重新Build上去了，如果錯誤提示有出現，即可close as complete.

請確認, 謝謝~

**Comment by leechiuhui** [comment]
仍然是這個錯誤訊息：Unable to process request due to missing initial sta This may happen if browser sessionStorage is inaccessible or accidentally cleared. Some specific scenarios are - 1) Using IDP-Initiated SAML SSO. 2 Using signInWithRedirect in a storage-partitioned browser environment.

沒有偵測到：
.catch((error) => {
console.error("Login error:", error);
if (error.message.includes('sessionStorage')) {
window.alert('瀏覽器不支持sessionStorage，請檢查瀏覽器設置或更換瀏覽器再試一次。');
}
});


有新開safari..

**Comment by leechiuhui** [comment]
更正：
目前只有這一種操作流
--->
[safari瀏覽器有先連結其他網站，若沒有則不會]->[接著從github mobile 上3dw-ato20-next專案上連結https://www.alearn.org.tw/ ,若直接在safari貼上連結網址則不會]

會造成出現這個錯誤訊息Unable to process request due to missing initial sta This may happen if browser sessionStorage is inaccessible or accidentally cleared. Some specific scenarios are - 1) Using IDP-Initiated SAML SSO. 2 Using signInWithRedirect in a storage-partitioned browser environment.

但是一直沒有出現window.alert('瀏覽器不支持sessionStorage，請檢查瀏覽器設置或更換瀏覽器再試一次。');

**Comment by leechiuhui** [comment]
https://github.com/3dw/auto20-next/assets/107933615/e6ebf6e9-e2c1-4e3e-bd2c-16ff54342074

**Comment by bestian** [comment]
試圖更正：
https://chatgpt.com/share/53641779-7961-470b-be9b-0e06e58df6cb

用強制重新定向到"/profile"頁

rebuild之後應該已經可以解決了

請確認後close this issue, 謝謝

**Comment by leechiuhui** [comment]
清除Safari所有瀏覽紀錄，重新測試仍然不行。如下影片，不過突然想到，除了開發者，使用者應該不會從GitHub連過去,所以⋯⋯https://github.com/3dw/auto20-next/assets/107933615/64168354-a6d3-4683-9e15-196c00e755fe

**Comment by bestian** [comment]
如果只有開發者會遇到，應該可以先忽略？

**Comment by leechiuhui** [comment]
對..，所以..先close
