### ISSUE TITLE
地圖介面

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#7]
use [vue-leaflet](
https://github.com/vue-leaflet/vue-leaflet)

放在MapView.vue上

**Comment by leechiuhui** [comment]
https://www.ioa.tw/Develop/GoogleMaps-Marker-Clustering.html
當 [Marker](https://developers.google.com/maps/documentation/javascript/markers?hl=zh-tw) 太多時，視角一拉遠後全部 Marker 擠在一起的困擾吧！預計研究處理這個。

**Comment by bestian** [comment]
merged into 
#24
