### ISSUE TITLE
側欄有問題，router-link有的點不到

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#80]

**Comment by leechiuhui** [comment]
點選側欄沒有發現點不到的問題，倒是如下圖，電腦版為何「登入」按鈕要被發配到那麼右邊...
<img width="1512" alt="截圖 2024-05-25 晚上9 25 56" src="https://github.com/3dw/auto20-next/assets/107933615/717fb507-7082-413f-a304-640bdc452fc5">

**Comment by leechiuhui** [comment]
[不斷點選過程中，出現下圖錯誤訊息
![Uploading 截圖 2024-05-25 晚上9.22.12.png…]()

**Comment by leechiuhui** [comment]
不斷點選過程中，出現下圖錯誤訊息
<img width="1512" alt="截圖 2024-05-25 晚上9 22 12" src="https://github.com/3dw/auto20-next/assets/107933615/7b386adf-9a9c-4ce0-9c70-c630de159622">
