### ISSUE TITLE
需要添加polis圖表的白話文解說

### ISSUE THREAD

**Issue by leechiuhui** [3dw/auto20-next#81]
<img width="1019" alt="截圖 2024-05-25 晚上9 32 59" src="https://github.com/3dw/auto20-next/assets/107933615/8df1a01f-ce75-4494-96b7-1b89887e6c76">

**Comment by bestian** [comment]
> <img alt="截圖 2024-05-25 晚上9 32 59" width="1019" src="https://private-user-images.githubusercontent.com/107933615/333803633-8df1a01f-ce75-4494-96b7-1b89887e6c76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NzM3MjcsIm5iZiI6MTcxNjY3MzQyNywicGF0aCI6Ii8xMDc5MzM2MTUvMzMzODAzNjMzLThkZjFhMDFmLWNlNzUtNDQ5NC05NmI3LTFiODk4ODdlNmM3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQyMTQzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGQ2NTM2MWY3NWM0ZGU0ZDMxNTMwMDI3MzVjZjI5MTY5NDI1Y2U0MjFjMmMwODI4NGVjOTQxZDlmYzAxN2E3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IobY6uYCpUG3OTny0TS6bo5BYekZxOBiKpr9UlGPGNs">

如果意見有分眾的話，它會群集類似意見的人，把他們分組。
