### ISSUE TITLE
讓每個頁面在沒有uid 或沒有users 時，顯示層有fallback

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#93]
- [x] 朋友頁
- [x] 地圖頁
- [x] 首頁
- [x] 社團頁
- [x] 單一社團頁

**Comment by leechiuhui** [comment]
will be back to work on this issue and this project until next Tuesday, 6/25 .

**Comment by leechiuhui** [comment]
I will spend today working on this issue... It might take a while...

**Comment by bestian** [comment]
它有work.
它是在使用者資料被讀到之前，會呈現出來的google Login按鈕.

因為之後會在Firebase改Rule, 讓用戶一要先登入，才能讀到users的資料, 以預防分散式攻擊, 和增進新用戶填表的意願.

登入後解鎖的概念~

**Comment by leechiuhui** [comment]
It seems to have worked successfully. Thank you for your guidance, teacher. I was able to understand it after just ten minutes of careful reading.
<img width="983" alt="截圖 2024-06-18 下午11 35 05" src="https://github.com/3dw/auto20-next/assets/107933615/f1c6ffa2-0281-4ad5-bab6-5a659fa75eda">

**Comment by leechiuhui** [comment]
haha...login method already exits.眼殘。
